#include "icons.h"

GBitmap* RESOURCE_ID_THERMOMETER_ICON_VAR = NULL;
GBitmap* RESOURCE_ID_KEY_ICON_VAR = NULL;
GBitmap* RESOURCE_ID_PERSON_ICON_VAR = NULL;
GBitmap* RESOURCE_ID_HUMIDITY_ICON_VAR = NULL;
GBitmap* RESOURCE_ID_LIGHTNING_ICON_VAR = NULL;
GBitmap* RESOURCE_ID_MONEY_ICON_VAR = NULL;
GBitmap* RESOURCE_ID_DRINK_ICON_VAR = NULL;
GBitmap* RESOURCE_ID_ALPHA_ICON_VAR = NULL;
GBitmap* RESOURCE_ID_BETA_ICON_VAR = NULL;
GBitmap* RESOURCE_ID_GAMMA_ICON_VAR = NULL;
GBitmap* RESOURCE_ID_BETAGAMMA_ICON_VAR = NULL;

void free_icons () {
  if (RESOURCE_ID_PERSON_ICON_VAR) {
    gbitmap_destroy(RESOURCE_ID_PERSON_ICON_VAR);
  }

  if (RESOURCE_ID_THERMOMETER_ICON_VAR) {
    gbitmap_destroy(RESOURCE_ID_THERMOMETER_ICON_VAR);
  }

  if (RESOURCE_ID_KEY_ICON_VAR) {
    gbitmap_destroy(RESOURCE_ID_KEY_ICON_VAR);
  }

  if (RESOURCE_ID_HUMIDITY_ICON_VAR) {
    gbitmap_destroy(RESOURCE_ID_HUMIDITY_ICON_VAR);
  }

  if (RESOURCE_ID_LIGHTNING_ICON_VAR) {
    gbitmap_destroy(RESOURCE_ID_LIGHTNING_ICON_VAR);
  }

  if (RESOURCE_ID_MONEY_ICON_VAR) {
    gbitmap_destroy(RESOURCE_ID_MONEY_ICON_VAR);
  }

  if (RESOURCE_ID_DRINK_ICON_VAR) {
    gbitmap_destroy(RESOURCE_ID_DRINK_ICON_VAR);
  }

  if (RESOURCE_ID_ALPHA_ICON_VAR) {
    gbitmap_destroy(RESOURCE_ID_ALPHA_ICON_VAR);
  }

  if (RESOURCE_ID_BETA_ICON_VAR) {
    gbitmap_destroy(RESOURCE_ID_BETA_ICON_VAR);
  }

  if (RESOURCE_ID_GAMMA_ICON_VAR) {
    gbitmap_destroy(RESOURCE_ID_GAMMA_ICON_VAR);
  }

  if (RESOURCE_ID_BETAGAMMA_ICON_VAR) {
    gbitmap_destroy(RESOURCE_ID_BETAGAMMA_ICON_VAR);
  }
}
